# URL de conexión (Asegúrate de poner tu endpoint de AWS y el nombre de tu BD)
spring.datasource.url=jdbc:mysql://52.0.164.75:3306/git_together_bbdd

# Credenciales de AWS
spring.datasource.username=gittogether
spring.datasource.password=gittogether123

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de Hibernate (update crea las tablas automáticamente si no existen)
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (muy útil para el TFG)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080

# Motor InnoDB
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# AWS S3
aws_access_key_id=ASIATCKARVWQLN5T4YLJ
aws_secret_access_key=smo8Ksfo212r4X34jtz+/eevzuglb7laWvz84aRf
aws_session_token=IQoJb3JpZ2luX2VjEIn//////////wEaCXVzLXdlc3QtMiJIMEYCIQDjNbkeJDZ/ZSbaE5zVj+KQS0gz0zbsme4LS2T8XE4pQgIhAKv4x8B86Q6Ic4iYC0I/6hMD9xv4cB/+LFUaTDsjZtI5KrsCCFIQABoMMjExMTI1NjQ0NzA0Igzt+jMv1ZaS0eUN80EqmAKYQ6AHPDwZEdP61W8Zjr5uJIURo2726qqTS1Sva8PizDSbLO3HwpActNTiIOBdn6c8kcPha5yGbRrlhP5SNG1ignCzYROCoCtbK6XdmrPjkC1SeLnWAyct4epG6vxAtWKslXiundNMyObvALDVZ1UpwZ1urSVWLyu8FgoW1CFBd2qKTHuCglng8sqKk5Rwg8INUeOhcsjzSjNziYcKLa33IYEOfmD5JNXvyeVK/RFKOUJ9OxW2Or6NSw6iCbqzAqAo09LHxZIzllMftUlr7F0Z6+0W6bOcA38fcK5WHKLl/bcnhF6zuO2Yve4injtkHZR2hvE42o+yL5ey2bISyghWz03JG3sz2PvjVbtM7XMHyyeFaTRipHVBMKzto88GOpwBoofjU+2q+7BydGhGbSAcbM7+3UyYhRuwkvVLwg8jjUGv2vyRvTNkCwlJkOT7aaD5dkAx8ds05aXitMFnXG1S+uHBYNSPP+6jHeqeo/ce5dkkvB3qmX/8v2JhpUWXDt6fq97iCsfv983Xk0gIY3NSO/CYNmyLI9JgifML0/0pSfRfBJCkfpybvlPB1mfhavYe0rpxIpUnlFfgl3wR
aws.s3.region=us-east-1
aws.s3.bucket-name=s3-gittogether