# URL de conexion (Asegrate de poner tu endpoint de AWS y el nombre de tu BD)
spring.datasource.url=${DB_URL:jdbc:mysql://52.0.164.75:3306/git_together_bbdd}

# Credenciales de base de datos
spring.datasource.username=${DB_USERNAME:gittogether}
spring.datasource.password=${DB_PASSWORD:gittogether123}

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de Hibernate (update crea las tablas automticamente si no existen)
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080

# Limites de subida de archivos (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Motor InnoDB
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# AWS S3 (Claves externas para soporte de AWS Academy)
aws_access_key_id=${AWS_ACCESS_KEY_ID:}
aws_secret_access_key=${AWS_SECRET_ACCESS_KEY:}
aws_session_token=${AWS_SESSION_TOKEN:}
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_BUCKET:s3-gittogether}

# Silenciar logs de conexión de Hikari y Hibernate
logging.level.com.zaxxer.hikari=WARN
logging.level.org.hibernate.orm.connections.pooling=WARN