# URL de conexi�n (Aseg�rate de poner tu endpoint de AWS y el nombre de tu BD)
spring.datasource.url=jdbc:mysql://52.0.164.75:3306/git_together_bbdd

# Credenciales de AWS
spring.datasource.username=gittogether
spring.datasource.password=gittogether123

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de Hibernate (update crea las tablas autom�ticamente si no existen)
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (muy �til para el TFG)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080

# Motor InnoDB
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# AWS S3
aws_access_key_id=
aws_secret_access_key=
aws_session_token=
aws.s3.region=us-east-1
aws.s3.bucket-name=s3-gittogether